# https://taskfile.dev

version: '3'

includes:
  gitlab:
    taskfile: test/Taskfile.yml
    dir: test

dotenv:
  - .env

tasks:
  default:
    desc: local run
    env:
      DB_SEED: true
    cmds:
      - rm -f test.db
      - go run ./cmd/review-flow-bot/main.go {{ .CLI_ARGS }}
    silent: true

  mod:
    desc: run go mod tidy
    cmd: go mod tidy

  test:
    desc: go run of cmd/test
    cmd: go run ./cmd/test/test.go
